
language: ruby

sudo: false
dist: trusty

script:
  # not yet set up: - bundle exec rake rubocop
  - bundle exec rake test

rvm:
  - 2.3
  - 2.4
  - 2.5

gemfile:
  - Gemfile

matrix:
  fast_finish: true

notifications:
  email: false
